export const PRICE_UPDATE = "PRICE_UPDATE";
export const INGREDIENTS_UPDATE = "INGREDIENTS_UPDATE";
export const ADD_INGREDIENT = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENTS";
